package classroom;
import java.awt.*;

public class Calculator {
	public static void main(String[] args) {
		Frame F = new Frame("Calculator");
		Panel P1 = new Panel();
		Panel P2 = new Panel();
		TextField Display = new TextField(20);
		Button B0,B1,B2,B3,B4,B5,B6,B7,B8,B9;
		Button BAdd, BSub, BMul, BDiv, BEql, BCle;
		Ehandler E = new Ehandler(Display);
		B0 = new Button("0");
		B0.addActionListener(E);
		B1 = new Button("1");
		B1.addActionListener(E);
		B2 = new Button("2");
		B2.addActionListener(E);
		B3 = new Button("3");
		B3.addActionListener(E);
		B4 = new Button("4");
		B4.addActionListener(E);
		B5 = new Button("5");
		B5.addActionListener(E);
		B6 = new Button("6");
		B6.addActionListener(E);
		B7 = new Button("7");
		B7.addActionListener(E);
		B8 = new Button("8");
		B8.addActionListener(E);
		B9 = new Button("9");
		B9.addActionListener(E);
		BAdd = new Button("+");
		BAdd.addActionListener(E);
		BSub = new Button("-");
		BSub.addActionListener(E);
		BMul = new Button("X");
		BMul.addActionListener(E);
		BDiv = new Button("/");
		BDiv.addActionListener(E);
		BEql = new Button("=");
		BEql.addActionListener(E);
		BCle = new Button("C");
		BCle.addActionListener(E);
		GridLayout GL = new GridLayout(4,4);
		P2.setLayout(GL);
		P1.add(Display);
		P2.add(B0);
		P2.add(B1);
		P2.add(B2);
		P2.add(B3);
		P2.add(B4);
		P2.add(B5);
		P2.add(B6);
		P2.add(B7);
		P2.add(B8);
		P2.add(B9);
		P2.add(BAdd);
		P2.add(BSub);
		P2.add(BMul);
		P2.add(BDiv);
		P2.add(BEql);
		P2.add(BCle);	
		F.add(P1,BorderLayout.NORTH);
		F.add(P2,BorderLayout.CENTER);	
		BCle.setBackground(Color.decode("#ce9ee5"));
		F.setSize(300,200);
		F.setVisible(true);
		P1.setBackground(Color.BLACK);
		P2.setBackground(Color.BLACK);
	}
}